# This is a basic workflow to help you get started with Actions

name: wiki-index

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  wiki-page-index:
  
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print Workspace
        run: echo $GITHUB_WORKSPACE
      - name: Print path
        run: pwd
      - name: List initial files
        run: ls -la
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone githubwikipageindex repo
        uses: actions/checkout@v3
      - name: Show path
        run: pwd
      - name: Clone wiki files
        uses: actions/checkout@v3
        with:
          repository: paulsuh/githubwikipageindex.wiki
          path: wiki
      - name: Show path again
        run: pwd
      - name: list checkouts
        run: ls -la
      - name: check for curl
        run: which curl
      - name: check for wget
        run: which wget
    #       - name: Clone wiki
#        uses:
#      - name: build-index
#        uses: ./
#        id: indexer
#        env:
#          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          USER_EMAIL: ${{ secrets.YOUR_EMAIL }}
#          USER_NAME: ${{ github.repository_owner }}
