# This is a basic workflow to help you get started with Actions

name: wiki-index

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  wiki-page-index:
  
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: build-index
        uses: ./
        id: indexer
        with:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.YOUR_EMAIL }}
          GH_NAME: ${{ github.repository_owner }}
