# This is a basic workflow to help you get started with Actions

name: wiki-index

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  generate-wiki-page-index:
  
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Clone the wiki files
      - name: Clone wiki files
        uses: actions/checkout@v3
        with:
          repository: paulsuh/githubwikipageindex.wiki
          path: wiki
      # Retrieve the Python code
      - name: Retrieve the code
        run: >
          /usr/bin/curl 
          --remote-name
          --silent
          --show-error 
          https://raw.githubusercontent.com/paulsuh/githubwikipageindex/main/generate_wiki_page_index.py
      # Run the indexer
      - name: Run the indexer
        run: |
          /usr/bin/python3 generate_wiki_page_index.py --insert wiki
#      - name: Check the result
#        run: cat wiki/Home.md
      # commit the changes
      - name: Commit indexer output
        run: >
          /usr/bin/git 
          -C wiki
          commit 
          -m 'Automatic Github wiki tag indexer run'
      # Push the wiki back to Github
      - name: Push wiki files back up to Github
        run: >
          /usr/bin/git push wiki
