# This is a basic workflow to help you get started with Actions

name: wiki-index

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  wiki-page-index:
  
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Clone the wiki files
      - name: Clone wiki files
        uses: actions/checkout@v3
        with:
          repository: paulsuh/githubwikipageindex.wiki
          path: wiki
      # Retrieve the Python code
      - name: Retrieve the code
        run: /usr/bin/curl -O https://raw.githubusercontent.com/paulsuh/githubwikipageindex/main/generate_wiki_page_index.py
      - name: Print Workspace
        run: echo $GITHUB_WORKSPACE
      - name: List initial files
        run: ls -la

#      - name: build-index
#        uses: ./
#        id: indexer
#        env:
#          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          USER_EMAIL: ${{ secrets.YOUR_EMAIL }}
#          USER_NAME: ${{ github.repository_owner }}
